name: CI Build
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
permissions:
    contents: write
jobs:
    ci:
        if: github.actor != 'github-actions[bot]'
        runs-on: ubuntu-latest
        environment: notifications # Thêm dòng này nếu dùng Environment Secrets
        strategy:
            matrix:
                node_version: [20]
        steps:
            # kéo repo về máy ảo của github, các lệnh sau đó thực thi tại thư mục gốc của repo
            - name: checkout code
              uses: actions/checkout@v4
              with:
                  persist-credentials: true
            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.node_version}}
                  cache: 'npm'
            # tai sao lại dùng npm ci thay vì npm install: https://docs.npmjs.com/cli/v9/commands/npm-ci
            - name: install dependencies
              run: npm ci
            - name: Type check
              run: npm run type-check --if-present
            - name: format
              run: npm run format
            - name: Notify if code is not format
              run: |
                  # kiểm tra có thay đổi không
                  if git diff --quiet; then
                    echo "✅ Code is properly formatted"
                  else
                    echo "❌ Code is not formatted!"
                    # Gửi thông báo Telegram
                    MESSAGE="⚠️ *Formatting Check Failed*%0A%0A"
                    MESSAGE+="Repository: ${{ github.repository }}%0A"
                    MESSAGE+="Branch: ${{ github.ref_name }}%0A"
                    MESSAGE+="Commit: ${{ github.sha }}%0A"
                    MESSAGE+="Author: ${{ github.actor }}%0A%0A"
                    MESSAGE+="Please run \`npm run format\` locally and commit the changes."
                    
                    curl -s -X POST "https://api.telegram.org/bot8573454294:AAEdg8NHw-gW6b454Whx4Wj2WMCKS2BKzKI/sendMessage" \
                      -d chat_id="5223925510" \
                      -d text="$MESSAGE" \
                      -d parse_mode="Markdown"
                    
                    exit 1
                  fi
            - name: build proj
              run: npm run build
            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build-output
                  path: dist
